### ISSUE TITLE
[FEA] Testing Feast in the multi-stage recommender pipeline for list type columns (multi-hot categorical)

### ISSUE THREAD

**Issue by mkumari-ed** [NVIDIA-Merlin/systems#113]
# 🚀 Feature request

Currently materializing features using feast fails if there is a list type column i.e. multi-hot categorical feature in the dataset. We need some testing done around if feast supports such features or is it a MM issue and needs more deep dive engineering effort.

## Motivation

This feature request is related to another GitHub issue https://github.com/NVIDIA-Merlin/Merlin/issues/361

## Your contribution

I am going to test on my end without using nvtabular for ETL if feast materialization goes through for such column in the dataset
![feast_materialization_failure](https://user-images.githubusercontent.com/28987826/172671133-b3849746-3672-42ec-8bf2-292d244e5334.png)
![Screen Shot 2022-06-08 at 8 23 39 AM](https://user-images.githubusercontent.com/28987826/172671194-9abe0df1-92f5-4bab-ad7e-1a2035265814.png)

**Comment by karlhigley** [comment]
@rnyak I think the simplest way to make sure this is covered by our tests might be to add a list features to the multi-stage example notebook, since that has all the required Feast set up that's a bit difficult to replicate in a (non-notebook) plain Python unit test. Is there a reasonable list feature we could add there using the current dataset?

**Comment by rnyak** [comment]
@mkumari-ed I am closing this since you could materialize the features after you set the dtype correctly in the feast feature config file. you can open it again if you still have materialize issue.
