### ISSUE TITLE
[BUG] Inference workflow doesn't honor input schema if TransformWorkflow renames a column

### ISSUE THREAD

**Issue by radekosmulski** [NVIDIA-Merlin/systems#195]
### Bug description
If I rename a column in my workflow, as follows:
`user_id  = ['userId'] >> nvt.ops.Rename(name='user_id') >> nvt.ops.Categorify() >> nvt.ops.TagAsUserID()`

This is what will happen:
![image](https://user-images.githubusercontent.com/2444926/188414988-36ab387e-6bdc-40f6-8ff8-be4654a317e1.png)

That causes an issue because in inference, I will send `userId` to triton expecting it to be renamed, but instead an error will be raised as follows
![image](https://user-images.githubusercontent.com/2444926/188415282-c4b28acb-dd2d-4b5b-9c6d-2e2d4280c780.png)

### Steps/Code to reproduce bug
The Implicit serving notebook being worked on under #194 is the reproducer. All you have to do in order to get the error is to replace how the column is renamed there with the following line (rename the column in the workflow and not outside as is being done there now):

`user_id  = ['userId'] >> nvt.ops.Rename(name='user_id') >> nvt.ops.Categorify() >> nvt.ops.TagAsUserID()`

### Environment details
current main

**Comment by karlhigley** [comment]
I think the schemas are actually correct here. Here's a slightly adjusted version of the ensemble definition cells that makes it clearer what's happening:
![Screenshot from 2022-09-06 12-05-47](https://user-images.githubusercontent.com/885295/188683662-cfaf3f01-c50c-4052-bbbd-be36fcc0d904.png)
What gets passed to the `Ensemble` class is just the final op in the graph, which all the other ops are connected to via parent/child relationships. Since the final op in the graph is the `PredictImplicit` operator, the schemas of that op reflect what `PredictImplicit` expects to receive, which has already been changed by `TransformWorkflow` from `userId` to `user_id`:
![Screenshot from 2022-09-06 12-06-15](https://user-images.githubusercontent.com/885295/188683919-676d8402-32e1-4869-9fb3-be5bc8b02c01.png)

**Comment by karlhigley** [comment]
With this version of the ensemble (and probably the original too?), the last remaining change required to make the notebook work as expected is to change the line:
```python
ten_examples = train.compute()['user_id'].sample(10).sort_values().to_frame().reset_index(drop=True)
```
to
```python
ten_examples = train.compute()['userId'].sample(10).sort_values().to_frame().reset_index(drop=True)
```
(since the ensemble expects the raw data before it's transformed by the workflow)
